# Site settings
title: Falko Buschke
email: falko.buschke@gmail.com
description: Macroecologist and conservation biologist
# this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site
logo: /img/Full logo.png

linkedin_username: falkobuschke
google_scholar: h7IuV9MAAAAJ&view_op=list_works&sortby=pubdate 
github_username:  falko-buschke
google_analytics: G-C4D570DNMX

# Build settings
markdown: kramdown
#theme: jekyll-theme-minimal

theme: jekyll-whiteglass
plugins:
  - jekyll-archives
  - jekyll-paginate
  - jekyll-sitemap

permalink: /:year/:month/:day/:title/
paginate_path: /posts/:num/
paginate: 5

jekyll-archives:
  enabled:
    - categories
    - tags
  layout: category_archives
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/
