# Site settings
title: Falko Buschke
email: falko.buschke@gmail.com
description: Macroecologist and conservation biologist
# this means to ignore newlines until "baseurl:"
avatar: https://solitaryecology.files.wordpress.com/2015/07/startup_small-logo.png 
baseurl: "" # the subpath of your site, e.g. /blog/
url: "" # the base hostname & protocol for your site

linkedin_username: falkobuschke
google_scholar: h7IuV9MAAAAJ&view_op=list_works&sortby=pubdate 
github_username:  falko-buschke

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
